Nosto/nosto-autocomplete

package.json
https://nostosolutions.atlassian.net/browse/CFE-88
=> Build alignment

src/mustache.ts
=> feat: test release

src/mustache.ts
=> feat: main release

.eslintrc.json, package-lock.json, package.json, src/autocomplete.ts, src/liquid.ts, src/mustache.ts, src/utils/dropdown.ts, src/utils/limiter.ts, src/utils/promise.ts
https://nostosolutions.atlassian.net/browse/CFE-153
=> Validate promise usage

.eslintrc.json, src/api/client.ts, src/search.ts, src/shims.d.ts, src/utils/dom.ts, src/utils/dropdown.ts, src/utils/ga.ts, src/utils/history.ts, src/utils/limiter.ts, src/utils/state.ts
https://nostosolutions.atlassian.net/browse/CFE-153
=> Fix type assertions

src/config.ts, src/utils/dom.ts, src/utils/input.ts
=> Simplify selector type

package-lock.json, package.json
Reverts Nosto/nosto-autocomplete#39
=> Revert "deps: bump eslint from 8.57.1 to 9.11.0"

eslint.config.mjs, package-lock.json, package.json
=> Use eslint 9 config

.github/workflows/release.yml
Use nosto-cicd bot token instead. Secret needs to be added by the ops team.
https://nosto.slack.com/archives/G02QR53TR/p1731533135201159
=> fix: switch release token to RELEASE_PAT_TOKEN

spec/suites/autocomplete.ts
=> Improve Mock types

package-lock.json, spec/suites/autocomplete.ts
=> Improve nostojs mocking

spec/build.spec.ts
=> Add test that verifies dist structure

package.json, spec/build.spec.ts, src/index.ts
=> Add base export back

package.json, spec/custom.spec.ts, spec/liquid.spec.ts, spec/mustache.spec.ts, spec/react.spec.ts, spec/suites/autocomplete.ts, src/api/client.ts, src/autocomplete.ts, src/config.ts, src/defaults/Autocomplete.tsx, src/entries/liquid.ts, src/entries/mustache.ts, src/liquid.ts, src/mustache.ts, src/search.ts, src/shims.d.ts, src/utils/dom.ts, src/utils/dropdown.ts, src/utils/ga.ts, src/utils/history.ts, src/utils/input.ts, src/utils/limiter.ts, src/utils/promise.ts, src/utils/state.ts
Changes
* flatten some function declarations
* align prettier settings with Nosto conventions
=> Flatten declarations

package.json, rollup.config.mjs, spec/build.spec.ts
=> Externalize lib deps

spec/liquid.spec.ts, spec/mustache.spec.ts, spec/utils.ts, src/liquid.ts, src/mustache.ts
=> Use fetch instead of XHR

.github/workflows/publish-docs.yml, .github/workflows/release.yml
=> Bump node version

src/api/client.ts, src/autocomplete.ts, src/utils/dropdown.ts, src/utils/ga.ts, src/utils/history.ts
=> Add logger proxy

package.json, scripts/exportTemplates.js, src/config.ts, src/defaults/Autocomplete.tsx, src/defaults/_generated.ts, src/entries/base.ts, src/entries/liquid.ts, src/entries/mustache.ts, src/entries/react.ts, src/search-js/decorator.ts
=> Modularize docs

src/search-js/currencies.ts
=> fix: Fix eslint errors

spec/custom.spec.ts, spec/decorators.spec.ts
=> Add autocomplete level test for decorators

eslint.config.mjs, package-lock.json, package.json, src/entries/liquid.ts, src/entries/mustache.ts, src/entries/preact.ts, src/entries/react.ts, src/index.ts, src/search-js/index.ts
=> Limit barrel file usage

.github/pull_request_template.md, .github/workflows/release.yml
Simplifying the PR template for consistency.
Also bumps the action version as CI didn't want to run on the old one.
=> chore: update pr template

package-lock.json, package.json, spec/suites/autocomplete.ts, src/api/client.ts, src/autocomplete.ts, src/search.ts
Changes
* update search-js dependency
* use better facades for nostojs functions
* simplify search function facade
=> Improve nostojs usage

package-lock.json, package.json, spec/build.spec.ts, spec/custom.spec.ts, spec/debounce.spec.ts, spec/decorators.spec.ts, spec/liquid.spec.ts, spec/mustache.spec.ts, spec/react.spec.ts, spec/search-js/decorator.spec.ts, spec/search-js/formatting.spec.ts, spec/search-js/search.spec.ts, spec/suites/autocomplete.ts, spec/utils.ts, tsconfig.json, vitest.config.js, vitest.config.ts
https://nostosolutions.atlassian.net/browse/CFE-941
=> Convert tests to vitest

.github/workflows/publish-docs.yml, .github/workflows/release.yml
=> Bump versions in GH action configs

.github/workflows/release.yml
=> Bump version

.github/workflows/publish-docs.yml, package.json
Remove coverage calls that were dropped when moving from jest to vitest
=> Remove coverage calls

src/styles.css
https://nostosolutions.atlassian.net/browse/NS-11487
=> Replace align-items: start with flex-start for broader support

vitest.config.ts
=> BREAKING CHANGE: release trigger

dev/dummySearch.ts, index.html, package-lock.json, package.json, vite.config.ts
Preparations for proper dev mode:
* vite dependency added
* added placeholder index.html
* added dev script in package.json
=> Preparations for dev mode

package-lock.json, package.json
=> Bump react versions

spec/custom.spec.ts, src/lib/autocomplete.ts, src/utils/input.ts
Disable native autocomplete for input element
https://nostosolutions.atlassian.net/browse/CFE-958
=> feat: Disable native autocomplete

README.md, package-lock.json, package.json, rollup.config.mjs, spec/build.spec.ts, spec/handlebars.spec.ts, spec/liquid.spec.ts, spec/mustache.spec.ts, src/handlebars.ts, src/handlebars/autocomplete.handlebars, src/handlebars/fromHandlebarsTemplate.ts, src/lib/dropdown.ts, src/mustache/fromMustacheTemplate.ts, src/shims.d.ts, vite.config.ts
https://nostosolutions.atlassian.net/browse/CFE-951
=> Add handlebars support

package.json, release.config.js
=> Move semver config to file

src/handlebars/NostoAutocomplete.ts, src/lib/components.ts, src/liquid/NostoAutocomplete.ts, src/mustache/NostoAutocomplete.ts
=> chore: simplify initAutocomplete

src/handlebars/NostoAutocomplete.ts, src/liquid/NostoAutocomplete.ts, src/mustache/NostoAutocomplete.ts
=> chore: drop constructors

package-lock.json, package.json, vite.config.ts
=> chore: add test coverage threshold

src/lib/autocomplete.ts, src/lib/client.ts, src/lib/dropdown.ts, src/utils/ga.ts, src/utils/history.ts, vite.config.ts
=> chore: use logger from search-js

spec/routing.spec.ts, src/lib/autocomplete.ts, src/lib/config.ts, src/lib/dropdown.ts
Adds an ability to handle custom client side routing trough the provided configuration function
https://nostosolutions.atlassian.net/browse/NS-11687
=> feat: custom routing handling

dev/dummySearch.ts, package-lock.json, package.json, src/lib/autocomplete.ts
=> feat: bump search-js

package-lock.json, package.json, spec/suites/webcomponents.ts, src/lib/autocomplete.ts, src/lib/components.ts, src/lib/config.ts, src/utils/ga.ts
https://nostosolutions.atlassian.net/browse/CFE-1007
=> feat: add native submit
